name: Build and Check

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Build and Check
        run: nix build .#

      - name: List libmill Providers
        run: |
          {
            echo "libmill was built with the following providers:"
            nix run .# -- --list-providers | while read -r -d $'\n' name docURL; do
              echo "- [$name]($docURL)"
            done
          } >> $GITHUB_STEP_SUMMARY
